// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2.Data;

#nullable disable

namespace Parcial2.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial2.Models.autor", b =>
                {
                    b.Property<int>("id_Autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Autor"));

                    b.Property<string>("nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_Autor");

                    b.ToTable("autor", (string)null);
                });

            modelBuilder.Entity("Parcial2.Models.libro", b =>
                {
                    b.Property<int>("id_Libro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Libro"));

                    b.Property<string>("area")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("cover_Url")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("digital_Url")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("disponible_Fisico")
                        .HasColumnType("bit");

                    b.Property<string>("editorial")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("id_Libro");

                    b.ToTable("libro", (string)null);
                });

            modelBuilder.Entity("Parcial2.Models.libro_autor", b =>
                {
                    b.Property<int>("id_Libro_Autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Libro_Autor"));

                    b.Property<int>("id_Autor")
                        .HasColumnType("int");

                    b.Property<int>("id_Libro")
                        .HasColumnType("int");

                    b.HasKey("id_Libro_Autor");

                    b.ToTable("libro_autor", (string)null);
                });

            modelBuilder.Entity("Parcial2.Models.prestamo", b =>
                {
                    b.Property<int>("id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Usuario"));

                    b.Property<bool>("Devuelto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_Devolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_Prestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_Libro")
                        .HasColumnType("int");

                    b.Property<int>("id_Prestamo")
                        .HasColumnType("int");

                    b.HasKey("id_Usuario");

                    b.ToTable("prestamo", (string)null);
                });

            modelBuilder.Entity("Parcial2.Models.usuario", b =>
                {
                    b.Property<int>("id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Usuario"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("programa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_Usuario");

                    b.ToTable("usuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
